repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
    - id: go-fmt
    - id: go-imports
- repo: https://github.com/golangci/golangci-lint
  rev: v1.41.1
  hooks:
    - id: golangci-lint
- repo: https://github.com/troian/pre-commit-golang
  sha: HEAD
  hooks:
    - id: go-build